version: '3.8'
services:
  app:
    build: .
    image: houss12/kaddem-app:latest
    container_name: spring_boot_app
    ports:
      - "8089:8089"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_db:3306/kaddem?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:
      SERVER_PORT: 8089
      MANAGEMENT_ENDPOINTS_ENABLED: "true"
    depends_on:
      db:
        condition: service_healthy

  db:
          image: mysql:8.0
          container_name: mysql_db
          environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "true"
            MYSQL_DATABASE: kaddem
          ports:
            - "3306:3306"
          volumes:
            - db_data:/var/lib/mysql
          healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
            interval: 10s
            timeout: 5s
            retries: 5
volumes:
    db_data:
