pipeline {
    agent any
    environment {
        // Environment variable for the generated token
        SONARQUBE_TOKEN = ''
        NEXUS_REPO_URL = 'http://localhost:8081/repository/maven-public/'  // Nexus repo URL
    }
    stages {
        stage('Checkout') {
            steps {
                git branch: 'NidhalDalhoumi-5SE4-G8', url: 'https://github.com/Lamouchi-ale/kaddem.git', credentialsId: 'NidhalSecret'
            }
        }

        stage('Run Unit Tests') {
            steps {
                script {
                    sh 'chmod +x mvnw'
                    sh './mvnw test'
                }
            }
        }

        stage('Build JAR') {
            steps {
                script {
                    sh 'mvn clean package'
                }
            }
        }

        stage('Deploy to Nexus') {
            steps {
                script {
                    sh 'mvn deploy -DskipTests'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    // Ensure the correct Dockerfile and context are used
                    dockerImage = docker.build("azizaydi/kaddem-app:${env.BUILD_ID}", '.')
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                script {

                    docker.withRegistry('https://index.docker.io/v1/', 'dckr_pat_MkSX4zHHX0zHtGw1VuzPJT0wWh8') {
                        dockerImage.push()
                    }
                }
            }
        }
    }
}
